In [9]:
a = [1,2,3,4,["data science",["machine learning"]]]
a[4][0][0:2].upper() + a[4][1][0][0:2].upper()

'DAMA'

In [15]:
type(a)

list

In [3]:
import numpy as np
x = [2,4,6,8]
y = np.array(x)
type(y)

numpy.ndarray

In [18]:
np.random.randint(5,10)

5

In [23]:
np.random.randint(5,10,3)

array([9, 6, 9])

In [31]:
data = np.random.randint(5,10,(5,3))

In [21]:
y/2

array([1., 2., 3., 4.])

In [25]:
y.shape

(4,)

In [28]:
z.shape

(5, 3)

In [33]:
distance = data[0] - data
distance

array([[ 0,  0,  0],
       [-1, -1, -2],
       [ 2, -2, -3],
       [ 2,  0,  0],
       [-2, -2, -2]])

In [37]:
distance = distance * distance
distance

array([[ 0,  0,  0],
       [ 1,  1, 16],
       [16, 16, 81],
       [16,  0,  0],
       [16, 16, 16]])

In [41]:
np.sqrt(distance.sum(axis=1))[1:]

array([ 4.24264069, 10.63014581,  4.        ,  6.92820323])

In [42]:
np.sqrt(distance.sum(axis=1))[1:].min()

4.0

In [43]:
np.sqrt(distance.sum(axis=1))[1:].argmin()

2

In [44]:
np.random.rand(10)

array([0.32087326, 0.24668741, 0.13215665, 0.09696702, 0.4600748 ,
       0.0089515 , 0.99133322, 0.75627594, 0.50744169, 0.99865361])

In [45]:
np.random.randn(10)

array([ 0.39788713,  0.32409466,  0.33162957,  0.93525374,  0.7988011 ,
        0.52411433,  1.23694819, -1.35235621,  0.15071717, -0.12639512])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
data = np.random.randint(0,10,(5,3))
data

array([[1, 3, 3],
       [7, 7, 2],
       [9, 6, 3],
       [8, 7, 1],
       [3, 9, 5]])

In [58]:
data.sum()

74

In [59]:
data.sum(axis=1)

array([ 7, 16, 18, 16, 17])

In [61]:
data.sum(axis=0)

array([28, 32, 14])

In [62]:
data[2:,:].sum()

51

In [63]:
data[2:,:].sum(axis=1)

array([18, 16, 17])

In [64]:
data[2:,:].sum(axis=0)

array([20, 22,  9])

In [65]:
data.mean()

4.933333333333334

In [66]:
data.mean(axis=1)

array([2.33333333, 5.33333333, 6.        , 5.33333333, 5.66666667])

In [67]:
data.mean(axis=0)

array([5.6, 6.4, 2.8])

In [68]:
data.var()

7.395555555555557

In [69]:
data.var(axis=1)

array([0.88888889, 5.55555556, 6.        , 9.55555556, 6.22222222])

In [70]:
data.var(axis=0)

array([9.44, 3.84, 1.76])

In [71]:
data.std()

2.7194770739161522

In [72]:
data.std(axis=1)

array([0.94280904, 2.3570226 , 2.44948974, 3.09120617, 2.49443826])

In [73]:
data.std(axis=0)

array([3.0724583 , 1.95959179, 1.32664992])

#### Nearest Neighbour Algorithm

In [4]:
data = np.random.randint(35,100,(10,5))
data

array([[53, 89, 42, 91, 76],
       [48, 78, 65, 70, 44],
       [54, 60, 37, 53, 54],
       [61, 99, 84, 45, 88],
       [98, 72, 72, 88, 48],
       [62, 73, 98, 68, 45],
       [84, 80, 60, 38, 50],
       [62, 89, 75, 86, 88],
       [55, 74, 87, 86, 91],
       [84, 56, 37, 60, 98]])

In [6]:
passfail = np.random.randint(0,2,(10)) 
passfail

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0])

In [7]:
data[:,4] = passfail
data

array([[53, 89, 42, 91,  0],
       [48, 78, 65, 70,  1],
       [54, 60, 37, 53,  1],
       [61, 99, 84, 45,  1],
       [98, 72, 72, 88,  0],
       [62, 73, 98, 68,  0],
       [84, 80, 60, 38,  1],
       [62, 89, 75, 86,  1],
       [55, 74, 87, 86,  1],
       [84, 56, 37, 60,  0]])

In [9]:
newstudent = np.array([35,80,67,90])
newstudent

array([35, 80, 67, 90])

### For each student we should find the difference between the new students marks and their own marks

In [19]:
np.sqrt((newstudent - data[:,:4])**2).sum(axis=1).argmin()

1