In [ ]:
import numpy as np
from IPython.core.InteractiveShell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### Variable Types

### Statistics Type

In [31]:
##### Mean
import numpy as np
marks = np.random.randint(1,100,(25,5))
marks.shape
marks

array([[84, 39, 16, 40, 85],
       [22, 10, 71, 28, 99],
       [39, 67, 16, 57, 95],
       [90, 41, 83, 72, 20],
       [56, 19, 69, 61, 58],
       [55, 38, 38, 44, 81],
       [98, 93, 66, 39, 53],
       [36, 70, 76, 78, 49],
       [18, 58, 76, 35, 57],
       [80, 32, 47, 34, 13],
       [45, 41, 26, 83, 68],
       [96, 90, 10, 79, 43],
       [51, 41, 63, 68, 29],
       [83, 84, 73, 11,  8],
       [ 4, 30, 46, 25, 13],
       [62, 88, 61, 40, 98],
       [44, 44, 53, 76,  5],
       [52, 93, 79, 73, 80],
       [90, 57, 96, 16, 12],
       [50, 99,  2, 53, 95],
       [38,  1, 42, 86, 77],
       [45, 73, 75, 26, 40],
       [87, 11, 29, 97, 70],
       [22, 71, 64, 88, 33],
       [78, 82, 90, 50, 83]])

In [38]:
## come up with a 5*3 matrix that can hold the AM, GM, HM for each of the rows
from scipy.stats import gmean,hmean

arithmeticmeanarray = []
geometricmeanarray = []
harmonicmeanarray = []
for i in range(0,5):
    subjectmarks = marks[:,i]
    arithmeticmeanarray.append(subjectmarks.mean())
    geometricmeanarray.append(gmean(subjectmarks))
    harmonicmeanarray.append(hmean(subjectmarks))

print(arithmeticmeanarray)
print(geometricmeanarray)
print(harmonicmeanarray)

combinedmean = np.array([arithmeticmeanarray,geometricmeanarray,harmonicmeanarray])
combinedmean.shape
combinedmeantranspose = combinedmean.T
combinedmeantranspose.shape

[57.0, 54.88, 54.68, 54.36, 54.56]
[48.22913022162803, 41.800536057351984, 43.661787219675126, 47.831056543811385, 41.79016175587347]
[32.9820414739125, 15.37572770235912, 22.70342491090264, 40.127078620097826, 26.844849825159237]


(5, 3)

## IQR

In [46]:

q1 = np.quantile(marks[:,0],0.25)
q3 = np.quantile(marks[:,0],0.75)

iqr = q3 - q1

## find outliers by taking value 1.5 times greater than IQR or 1.5 times lesser than IQR

utv = q3 + (1.5*iqr)
ltv = q1 - (1.5*iqr)

print(utv,ltv)
marks[1,0] = 500
print(marks)

for i in marks[:,0]:
    if((i> utv) or (i<ltv)):
        print('outlier -> ', i)

149.0 -27.0
[[ 84  39  16  40  85]
 [500  10  71 500  99]
 [ 39  67  16  57  95]
 [ 90  41  83  72  20]
 [ 56  19  69  61  58]
 [ 55  38  38  44  81]
 [ 98  93  66  39  53]
 [ 36  70  76  78  49]
 [ 18  58  76  35  57]
 [ 80  32  47  34  13]
 [ 45  41  26  83  68]
 [ 96  90  10  79  43]
 [ 51  41  63  68  29]
 [ 83  84  73  11   8]
 [  4  30  46  25  13]
 [ 62  88  61  40  98]
 [ 44  44  53  76   5]
 [ 52  93  79  73  80]
 [ 90  57  96  16  12]
 [ 50  99   2  53  95]
 [ 38   1  42  86  77]
 [ 45  73  75  26  40]
 [ 87  11  29  97  70]
 [ 22  71  64  88  33]
 [ 78  82  90  50  83]]
outlier ->  500
