In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [3]:
data = np.random.randint(0,10,(4,3))
data

array([[8, 7, 6],
       [7, 9, 1],
       [2, 9, 7],
       [1, 4, 0]])

In [4]:
np.corrcoef(data)

array([[ 1.        ,  0.72057669, -0.69337525,  0.24019223],
       [ 0.72057669,  1.        ,  0.        ,  0.84615385],
       [-0.69337525,  0.        ,  1.        ,  0.53293871],
       [ 0.24019223,  0.84615385,  0.53293871,  1.        ]])

In [7]:
## Before this step, execute pip install opencv-python

import cv2
test = cv2.imread('D:\\sanooj\\datascience\\data\\SundayBreak2.jpeg')
cv2.imshow('image',test)
cv2.waitKey()
cv2.destroyAllWindows()

13

In [6]:
test.shape
type(test)

(320, 480, 3)

numpy.ndarray

In [25]:
test[0,0]

array([19, 12, 15], dtype=uint8)

In [8]:
test[100:300,200:400].shape

(200, 200, 3)

In [9]:
cv2.imshow('image',test[100:300,200:400])
cv2.waitKey()
cv2.destroyAllWindows()

13

### SET

In [8]:
a = {"a","b","c","d","a"}
type(a)

for i in a:
    print(i)

set

b
c
d
a


In [9]:
b = {"a","c","d"}

In [10]:
a-b

{'b'}

In [11]:
a.union(b)

{'a', 'b', 'c', 'd'}

In [13]:
a.intersection(b)

{'a', 'c', 'd'}

In [17]:
test = {'1','2','1','2'}
print(test)

test = {1,2,1,2}
print(test)

test = {1.1, 2.2, 1.1, 2.2}
print(test)

{'2', '1'}
{1, 2}
{1.1, 2.2}


### PANDAS (PANEL DATASETS)

In [10]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10,100,(3,3)), columns=['x1','x2','x3'], index=['r1','r2','r3'])
df

x1  x2  x3
r1  93  15  24
r2  47  72  21
r3  37  16  26

In [11]:
df.index

Index(['r1', 'r2', 'r3'], dtype='object')

In [12]:
df.columns

Index(['x1', 'x2', 'x3'], dtype='object')

In [13]:
df.values

array([[93, 15, 24],
       [47, 72, 21],
       [37, 16, 26]])

In [14]:
## if you extract a single column that's called a Series

df['x1']

type(df['x1'])

r1    93
r2    47
r3    37
Name: x1, dtype: int32

pandas.core.series.Series

In [15]:
## Series will have index and values

df['x1'].index

df['x1'].values

Index(['r1', 'r2', 'r3'], dtype='object')

array([93, 47, 37])

In [16]:
# Series doesn't have any columns
df['x1'].columns

AttributeError: 'Series' object has no attribute 'columns'

In [17]:
df=pd.DataFrame(np.random.randint(1,10,(3,3)))
df

0  1  2
0  8  3  2
1  8  4  7
2  9  8  2

In [18]:
df.index
df.columns
df.values

RangeIndex(start=0, stop=3, step=1)

RangeIndex(start=0, stop=3, step=1)

array([[8, 3, 2],
       [8, 4, 7],
       [9, 8, 2]])

In [19]:
## Credit Risk DataSet
df=pd.read_csv(r"D:\sanooj\datascience\data\home-credit-default-risk\application_test.csv")
df.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100001         Cash loans           F            N               Y   
1      100005         Cash loans           M            N               Y   
2      100013         Cash loans           M            Y               Y   
3      100028         Cash loans           F            N               Y   
4      100038         Cash loans           M            Y               N   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          135000.0    568800.0      20560.5         450000.0   
1             0           99000.0    222768.0      17370.0         180000.0   
2             0          202500.0    663264.0      69777.0         630000.0   
3             2          315000.0   1575000.0      49018.5        1575000.0   
4             1          180000.0    625500.0      32067.0         625500.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        0.0                        0.0   
4                        NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         0.0  
1                        0.0                         3.0  
2                        1.0                         4.0  
3                        0.0                         3.0  
4                        NaN                         NaN  

[5 rows x 121 columns]

In [24]:
df.shape

(48744, 121)

In [20]:
# df.mean() outputs a Series object, Also, the number of rows will here indicate the number of columns with numerical values
df_mean = df.mean()
print(df_mean)

SK_ID_CURR                    277796.676350
CNT_CHILDREN                       0.397054
AMT_INCOME_TOTAL              178431.805855
AMT_CREDIT                    516740.435561
AMT_ANNUITY                    29426.240209
                                  ...      
AMT_REQ_CREDIT_BUREAU_DAY          0.001803
AMT_REQ_CREDIT_BUREAU_WEEK         0.002787
AMT_REQ_CREDIT_BUREAU_MON          0.009299
AMT_REQ_CREDIT_BUREAU_QRT          0.546902
AMT_REQ_CREDIT_BUREAU_YEAR         1.983769
Length: 105, dtype: float64


In [22]:
type(df_mean)

pandas.core.series.Series

In [21]:
num_columns = df_mean.index
print(num_columns)

cat_columns = []
for i in df.columns:
    if i not in num_columns:
        cat_columns.append(i)

## QC check .. cat_columns + num_columns should be the total columns
len(cat_columns),len(num_columns),len(df.columns)

Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT',
       'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE',
       'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=105)


(16, 105, 121)

In [23]:
df.isna()

SK_ID_CURR  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  \
0           False               False        False         False   
1           False               False        False         False   
2           False               False        False         False   
3           False               False        False         False   
4           False               False        False         False   
...           ...                 ...          ...           ...   
48739       False               False        False         False   
48740       False               False        False         False   
48741       False               False        False         False   
48742       False               False        False         False   
48743       False               False        False         False   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                False         False             False       False   
1                False         False             False       False   
2                False         False             False       False   
3                False         False             False       False   
4                False         False             False       False   
...                ...           ...               ...         ...   
48739            False         False             False       False   
48740            False         False             False       False   
48741            False         False             False       False   
48742            False         False             False       False   
48743            False         False             False       False   

       AMT_ANNUITY  AMT_GOODS_PRICE  ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  \
0            False            False  ...             False             False   
1            False            False  ...             False             False   
2            False            False  ...             False             False   
3            False            False  ...             False             False   
4            False            False  ...             False             False   
...            ...              ...  ...               ...               ...   
48739        False            False  ...             False             False   
48740        False            False  ...             False             False   
48741        False            False  ...             False             False   
48742        False            False  ...             False             False   
48743        False            False  ...             False             False   

       FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  \
0                 False             False                       False   
1                 False             False                       False   
2                 False             False                       False   
3                 False             False                       False   
4                 False             False                        True   
...                 ...               ...                         ...   
48739             False             False                       False   
48740             False             False                        True   
48741             False             False                       False   
48742             False             False                       False   
48743             False             False                       False   

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                          False                       False   
1                          False                       False   
2                          False                       False   
3                          False                       False   
4                           True                        True   
...                          ...                         ...   
48739                      False                       False   

In [25]:
df.isna().sum()

SK_ID_CURR                       0
NAME_CONTRACT_TYPE               0
CODE_GENDER                      0
FLAG_OWN_CAR                     0
FLAG_OWN_REALTY                  0
                              ... 
AMT_REQ_CREDIT_BUREAU_DAY     6049
AMT_REQ_CREDIT_BUREAU_WEEK    6049
AMT_REQ_CREDIT_BUREAU_MON     6049
AMT_REQ_CREDIT_BUREAU_QRT     6049
AMT_REQ_CREDIT_BUREAU_YEAR    6049
Length: 121, dtype: int64

In [ ]:
## df.isna().sum() will indicate the number of rows per column, where there is a null value
## to find the % of null value for each column, we can divide sum/total .. we get the total from the first index of shape

In [26]:
null_values = (df.isna().sum() / df.shape[0]) * 100
null_values

SK_ID_CURR                     0.000000
NAME_CONTRACT_TYPE             0.000000
CODE_GENDER                    0.000000
FLAG_OWN_CAR                   0.000000
FLAG_OWN_REALTY                0.000000
                                ...    
AMT_REQ_CREDIT_BUREAU_DAY     12.409732
AMT_REQ_CREDIT_BUREAU_WEEK    12.409732
AMT_REQ_CREDIT_BUREAU_MON     12.409732
AMT_REQ_CREDIT_BUREAU_QRT     12.409732
AMT_REQ_CREDIT_BUREAU_YEAR    12.409732
Length: 121, dtype: float64

In [30]:
## Let's find the columns where there are < 30% null values .. we are going to consider these columns/fields for calculation
treatment_columns = null_values[null_values< 30].index

## Let's find the columns where there are > 30% null values .. we are going to drop these columns/fields for calculation
drop_columns = null_values[null_values> 30].index

In [31]:
treatment_columns
drop_columns

Index(['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR',
       'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT',
       'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'FLAG_MOBIL', 'FLAG_EMP_PHONE',
       'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL',
       'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START',
       'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION',
       'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION',
       'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY',
       'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_2',
       'EXT_SOURCE_3', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CN

Index(['OWN_CAR_AGE', 'OCCUPATION_TYPE', 'EXT_SOURCE_1', 'APARTMENTS_AVG',
       'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG',
       'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG',
       'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG',
       'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG',
       'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE',
       'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE',
       'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE',
       'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE',
       'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
       'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI',
       'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI',
       'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
       'NONLIVINGAPARTMENTS_MEDI', 'NONLI

In [32]:
treatment_columns.shape
drop_columns.shape

(71,)

(50,)

In [33]:
df.shape

(48744, 121)

In [34]:
df.drop(drop_columns,axis=1).shape

(48744, 71)

In [35]:
## in the above cell, even though we droped .. in the current cell number of columns is shown as 121 .. 
## i.e. the 50 columns were dropped only on the above cell session
df.shape

(48744, 121)

In [36]:
## to permanantly drop use inplace=True
df.drop(drop_columns,axis=1,inplace=True)

In [37]:
df.shape

(48744, 71)

In [39]:
num_columns = df.mean().index
print(num_columns)

cat_columns = []
for i in df.columns:
    if i not in num_columns:
        cat_columns.append(i)

len(cat_columns),len(num_columns),len(df.columns)

Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT',
       'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE',
       'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH',
       'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE',
       'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
       'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION',
       'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY',
       'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'EXT_SOURCE_2',
       'EXT_SOURCE_3', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE',
       'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3',
       'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6',
       'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9',
       'FLA

(11, 60, 71)

In [40]:
print(cat_columns)

['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE']


In [45]:
## As of above step, Null value treatment is done.. Now for the null value let's replace with Mode for the categorical  
## fields, for the numeric fields let's replace with Mode

## for the numeric field HOUR_APPR_PROCESS_START, find the median
df['HOUR_APPR_PROCESS_START'].median()

## for the categorical field CODE_GENDER find all the unique values
df['CODE_GENDER'].unique()
## for the categorical field CODE_GENDER find the number of unique values
df['CODE_GENDER'].nunique()
## for the categorical field CODE_GENDER find the occurences of each  unique value
df['CODE_GENDER'].value_counts()
## for the categorical field CODE_GENDER pick the value with the max occurrence .. that will be the Mode
df['CODE_GENDER'].value_counts().index[0]

12.0

array(['F', 'M'], dtype=object)

2

F    32678
M    16066
Name: CODE_GENDER, dtype: int64

'F'

In [46]:
## for all numeric columns, replace the null value with median
## for all categorical columns, replace the null value with the mode
for i in df.columns:
    if i  in num_columns:
        df[i].fillna(df[i].median(),inplace=True)
    else:
        df[i].fillna(df[i].value_counts().index[0],inplace=True)

In [47]:
df.describe()

SK_ID_CURR  CNT_CHILDREN  AMT_INCOME_TOTAL    AMT_CREDIT  \
count   48744.000000  48744.000000      4.874400e+04  4.874400e+04   
mean   277796.676350      0.397054      1.784318e+05  5.167404e+05   
std    103169.547296      0.709047      1.015226e+05  3.653970e+05   
min    100001.000000      0.000000      2.694150e+04  4.500000e+04   
25%    188557.750000      0.000000      1.125000e+05  2.606400e+05   
50%    277549.000000      0.000000      1.575000e+05  4.500000e+05   
75%    367555.500000      1.000000      2.250000e+05  6.750000e+05   
max    456250.000000     20.000000      4.410000e+06  2.245500e+06   

         AMT_ANNUITY  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
count   48744.000000     4.874400e+04                48744.000000   
mean    29424.651219     4.626188e+05                    0.021226   
std     16012.584824     3.367102e+05                    0.014428   
min      2295.000000     4.500000e+04                    0.000253   
25%     17973.000000     2.250000e+05                    0.010006   
50%     26199.000000     3.960000e+05                    0.018850   
75%     37390.500000     6.300000e+05                    0.028663   
max    180576.000000     2.245500e+06                    0.072508   

         DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  ...  FLAG_DOCUMENT_18  \
count  48744.000000   48744.000000       48744.000000  ...      48744.000000   
mean  -16068.084605   67485.366322       -4967.652716  ...          0.001559   
std     4325.900393  144348.507136        3552.612035  ...          0.039456   
min   -25195.000000  -17463.000000      -23722.000000  ...          0.000000   
25%   -19637.000000   -2910.000000       -7459.250000  ...          0.000000   
50%   -15785.000000   -1293.000000       -4490.000000  ...          0.000000   
75%   -12496.000000    -296.000000       -1901.000000  ...          0.000000   
max    -7338.000000  365243.000000           0.000000  ...          1.000000   

       FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count           48744.0           48744.0           48744.0   
mean                0.0               0.0               0.0   
std                 0.0               0.0               0.0   
min                 0.0               0.0               0.0   
25%                 0.0               0.0               0.0   
50%                 0.0               0.0               0.0   
75%                 0.0               0.0               0.0   
max                 0.0               0.0               0.0   

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count                48744.000000               48744.000000   
mean                     0.001846                   0.001580   
std                      0.043406                   0.043179   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      2.000000                   2.000000   

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count                48744.000000               48744.000000   
mean                     0.002441                   0.008145   
std                      0.050582                   0.103858   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      2.000000                   6.000000   

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
count               48744.000000                48744.000000  
mean                    0.479033                    1.985783  
std                     0.673449                    1.721001  
min                     0.000000                    0.000000  

In [48]:
## no more null values
df.isna().sum()

SK_ID_CURR                    0
NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
FLAG_OWN_REALTY               0
                             ..
AMT_REQ_CREDIT_BUREAU_DAY     0
AMT_REQ_CREDIT_BUREAU_WEEK    0
AMT_REQ_CREDIT_BUREAU_MON     0
AMT_REQ_CREDIT_BUREAU_QRT     0
AMT_REQ_CREDIT_BUREAU_YEAR    0
Length: 71, dtype: int64

In [49]:
df['CODE_GENDER'].head()

0    F
1    M
2    M
3    F
4    M
Name: CODE_GENDER, dtype: object

In [50]:
## we can convert CODE_GENDER , a categorical field into a numerical field using get_dummies approach
pd.get_dummies(df['CODE_GENDER']).head()

F  M
0  1  0
1  0  1
2  0  1
3  1  0
4  0  1

In [58]:
df['ORGANIZATION_TYPE'].value_counts()

Business Entity Type 3    10840
XNA                        9274
Self-employed              5920
Other                      2707
Medicine                   1716
Government                 1508
Business Entity Type 2     1479
Trade: type 7              1303
School                     1287
Construction               1039
Kindergarten               1038
Business Entity Type 1      887
Transport: type 4           884
Trade: type 3               578
Military                    530
Industry: type 9            499
Industry: type 3            489
Security                    472
Transport: type 2           448
Police                      441
Housing                     435
Industry: type 11           416
Bank                        374
Security Ministries         341
Services                    302
Postal                      294
Agriculture                 292
Restaurant                  284
Trade: type 2               242
University                  221
Industry: type 7            217
Industry

In [68]:
## Min Max Treatment
## For numerical fields, where the scale of the fields are different (e.g. some columns will have values ranging between 1-5,
## some other field will have values ranging from 1000-2000.. we need to bring them to unique scale.. we use min max scaling
## for achieving this)

## Xnew = (Xi) - min(X) /max(X) - min(X)

for i in num_columns:
    numerator = (df[i].values) - (df[i].values.min())
    denominator = (df[i].values.max()) - (df[i].values.min())
    if(denominator == 0):
        denominator = 1
    values = numerator/denominator
    df[i] = values

In [69]:
df.describe()

SK_ID_CURR  CNT_CHILDREN  AMT_INCOME_TOTAL    AMT_CREDIT  \
count  48744.000000  48744.000000      48744.000000  48744.000000   
mean       0.499077      0.019853          0.034563      0.214379   
std        0.289600      0.035452          0.023162      0.166052   
min        0.000000      0.000000          0.000000      0.000000   
25%        0.248581      0.000000          0.019520      0.097996   
50%        0.498382      0.000000          0.029787      0.184049   
75%        0.751032      0.050000          0.045187      0.286299   
max        1.000000      1.000000          1.000000      1.000000   

        AMT_ANNUITY  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
count  48744.000000     48744.000000                48744.000000   
mean       0.152174         0.189784                    0.290259   
std        0.089817         0.153015                    0.199684   
min        0.000000         0.000000                    0.000000   
25%        0.087940         0.081800                    0.134980   
50%        0.134080         0.159509                    0.257380   
75%        0.196855         0.265849                    0.393191   
max        1.000000         1.000000                    1.000000   

         DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  ...  FLAG_DOCUMENT_18  \
count  48744.000000   48744.000000       48744.000000  ...      48744.000000   
mean       0.511111       0.221968           0.790589  ...          0.001559   
std        0.242252       0.377179           0.149760  ...          0.039456   
min        0.000000       0.000000           0.000000  ...          0.000000   
25%        0.311250       0.038027           0.685556  ...          0.000000   
50%        0.526964       0.042252           0.810724  ...          0.000000   
75%        0.711150       0.044857           0.919863  ...          0.000000   
max        1.000000       1.000000           1.000000  ...          1.000000   

       FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count           48744.0           48744.0           48744.0   
mean                0.0               0.0               0.0   
std                 0.0               0.0               0.0   
min                 0.0               0.0               0.0   
25%                 0.0               0.0               0.0   
50%                 0.0               0.0               0.0   
75%                 0.0               0.0               0.0   
max                 0.0               0.0               0.0   

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count                48744.000000                48744.00000   
mean                     0.000923                    0.00079   
std                      0.021703                    0.02159   
min                      0.000000                    0.00000   
25%                      0.000000                    0.00000   
50%                      0.000000                    0.00000   
75%                      0.000000                    0.00000   
max                      1.000000                    1.00000   

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count                48744.000000               48744.000000   
mean                     0.001221                   0.001357   
std                      0.025291                   0.017310   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      1.000000                   1.000000   

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
count               48744.000000                48744.000000  
mean                    0.068433                    0.116811  
std                     0.096207                    0.101235  
min                     0.000000                    0.000000  
25%             