<h1> Day 2 - Class </h1>

## Lists & Numpy
In the previous class, we studied the basic datatypes : int, float and str. In this class we will see lists and numpy.

### Lists
List can hold items of multiple data types. In the example below, the list 'a' holds data of type int and lists

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [8]:
# Given the list 'a' , get the output DAMA
a = [1,2,3,4,["data science",["machine learning"]]]
a[4][0][0:2].upper() + a[4][1][0][0:2].upper()

'DAMA'

In [9]:
type(a)
type(a[0])
type(a[4])

list

int

list

#### Bulk operations on List
Let's try to add or divide the entire List in one go. It will not work and gives an error. Even the multiplication operation is not giving the intended result, it's just repeating the elements twice

In [13]:
a = [2,4,6,8]
a + 2

TypeError: can only concatenate list (not "int") to list

In [12]:
a = [2,4,6,8]
a * 2

[2, 4, 6, 8, 2, 4, 6, 8]

In [11]:
a = [2,4,6,8]
a / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### Numpy
In Python we have lists that serve the purpose of arrays, but they are slow to process.NumPy aims to provide an array object that is up to 50x faster that traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important. Numpy functions for working in domain of linear algebra, fourier transform, and matrices.

In short, NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

#### Features
It contains among other things:

- a powerful N-dimensional array object

- sophisticated (broadcasting) functions

- tools for integrating C/C++ and Fortran code

- useful linear algebra, Fourier transform, and random number capabilities

- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 

- Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

#### Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#### Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.


In [15]:
import numpy as np
x = [2,4,6,8]
y = np.array(x)
type(y)

y + 2

y * 2

y / 2

numpy.ndarray

array([ 4,  6,  8, 10])

array([ 4,  8, 12, 16])

array([1., 2., 3., 4.])

#### NumPy Functions
##### Random

In [41]:
data1 = np.random.randint(5,10)

data2 = np.random.randint(5,10,3)

data3 = np.random.randint(5,10,(5,3))

print('data1 -> A random number between 5 and 10 : \n', data1)
print()
print('data2 -> A list with 3 random numbers between 5 and 10 : \n', data2)
print()
print('data3 -> A list with 5 rows and 3 columns with random numbers between 5 and 10 : \n', data3)
print()

print('Shape of data2 is {} and shape of data3 is {}'.format(data2.shape, data3.shape))
print()
print('Type of data1 is {}, Type of data2 is {} and type of data3 is {}'.format(type(data1), type(data2), type(data3)))

data1 -> A random number between 5 and 10 : 
 8

data2 -> A list with 3 random numbers between 5 and 10 : 
 [5 7 5]

data3 -> A list with 5 rows and 3 columns with random numbers between 5 and 10 : 
 [[8 9 9]
 [8 6 8]
 [5 6 9]
 [5 5 5]
 [5 7 9]]

Shape of data2 is (3,) and shape of data3 is (5, 3)

Type of data1 is <class 'int'>, Type of data2 is <class 'numpy.ndarray'> and type of data3 is <class 'numpy.ndarray'>


In [59]:
# Generates 10 random numbers between 0 and 1
data4 = np.random.rand(10)

# Generates 10 random numbers which follows normal distribution
data5 = np.random.randn(10)

data4

data5

array([0.22465387, 0.9214794 , 0.36798175, 0.62879806, 0.50653279,
       0.27631806, 0.81299251, 0.52990775, 0.39745495, 0.26191832])

array([ 0.97489542,  1.12283699,  0.76613446,  0.43894349, -1.02704631,
        0.03302306, -0.20461281, -0.62667168,  1.07469535, -0.36596425])

In [60]:
# Generates an identity matrix(a matrix with all diagonal element 1 and all other elements 0)
np.eye(5)
# Generates a list of 5 zeroes
np.zeros(5)
# Generates a 5 * 5 list of all zeroes
np.zeros((5,5))
# Generates a list of 5 ones
np.ones(5)
# Generates a 5 * 5 list of all ones
np.ones((5,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### Math & statistical functions

In [64]:
data = np.random.randint(2,4,(3,4))
data
# Gives a 3*4 list with each value corresponding the square root of the elememts
np.sqrt(data)
# Sums up all the elements of the data and then finds square root
np.sqrt(data.sum())
# Sums up all the elements in a column, finds the square root. 
# Notice there are 4 elements in the output (corresponding to each column)
np.sqrt(data.sum(axis=0))
# Sums up all the elements in a row, finds the square root.
# Notice there are 3 elements in the output (corresponding to each row)
np.sqrt(data.sum(axis=1))

array([[2, 2, 2, 2],
       [3, 3, 2, 3],
       [2, 3, 2, 3]])

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.41421356, 1.73205081]])

5.385164807134504

array([2.64575131, 2.82842712, 2.44948974, 2.82842712])

array([2.82842712, 3.31662479, 3.16227766])

##### Mean, Standard Deviation, Variance

In [67]:
# Sum of all the elements inside data
data.sum()

# Sum of all the elements within each column
data.sum(axis=0)

# Sum of all the elements within each row
data.sum(axis=1)

# Mean of all the elements inside data
data.mean()

# Mean of all the elements within each column
data.mean(axis=0)

# Mean of all the elements within each row
data.mean(axis=1)

# Standard Deviation of all the elements inside data
data.std()

# Standard Deviation of all the elements within each column
data.std(axis=0)

# Standard Deviation of all the elements within each row
data.std(axis=1)

# Variance of all the elements inside data
data.var()

# Variance of all the elements within each column
data.var(axis=0)

# Variance of all the elements within each row
data.var(axis=1)

29

array([7, 8, 6, 8])

array([ 8, 11, 10])

2.4166666666666665

array([2.33333333, 2.66666667, 2.        , 2.66666667])

array([2.  , 2.75, 2.5 ])

0.49300664859163473

array([0.47140452, 0.47140452, 0.        , 0.47140452])

array([0.       , 0.4330127, 0.5      ])

0.2430555555555556

array([0.22222222, 0.22222222, 0.        , 0.22222222])

array([0.    , 0.1875, 0.25  ])

##### Min , Max, ArgMin, ArgMax

In [74]:
data = np.random.randint(2,10,(3,5))
data

array([[8, 5, 9, 5, 4],
       [8, 5, 5, 5, 9],
       [5, 2, 7, 5, 3]])

In [80]:
data.min()
data.max()
data.min(axis=0)
data.min(axis=1)
data.max(axis=0)
data.max(axis=1)

2

9

array([5, 2, 5, 5, 3])

array([4, 5, 2])

array([8, 5, 9, 5, 9])

array([9, 9, 7])

In [81]:
data.argmin()
data.argmax()
data.argmin(axis=0)
data.argmin(axis=1)
data.argmax(axis=0)
data.argmax(axis=1)

11

2

array([2, 2, 1, 0, 2], dtype=int64)

array([4, 1, 1], dtype=int64)

array([0, 0, 0, 0, 1], dtype=int64)

array([2, 4, 2], dtype=int64)

##### Ravel

In [83]:
data = np.random.randint(2,7,(3,5))
data

# Flattens out the entire array
data.ravel()

array([[5, 6, 4, 5, 6],
       [6, 5, 2, 6, 6],
       [4, 3, 3, 6, 4]])

array([5, 6, 4, 5, 6, 6, 5, 2, 6, 6, 4, 3, 3, 6, 4])

##### List selecting only partial rows/columns

In [84]:
data

array([[5, 6, 4, 5, 6],
       [6, 5, 2, 6, 6],
       [4, 3, 3, 6, 4]])

In [85]:
# select only first two rows. Note index starts at 0. 0:2 -> select 0,1
data[0:2]

array([[5, 6, 4, 5, 6],
       [6, 5, 2, 6, 6]])

In [87]:
#select only last two rows. 1:3 -> select 1,2
data[1:3]

array([[6, 5, 2, 6, 6],
       [4, 3, 3, 6, 4]])

In [91]:
# Notice the below syntax 
# data[row_start:row_end, column_start:column_end]
# If we don't mention any numbers, then it selects everything
data[:,:]

array([[5, 6, 4, 5, 6],
       [6, 5, 2, 6, 6],
       [4, 3, 3, 6, 4]])

In [90]:
# select only first two columns. 
# Notice the syntax, select all rows, but restrict columns 0,1
data[:,0:2]

array([[5, 6],
       [6, 5],
       [4, 3]])

In [92]:
# select 4th and 5th column
data[:,3:5]

array([[5, 6],
       [6, 6],
       [6, 4]])

In [94]:
# select 1st and 3rd column
data[:,[0,3]]

array([[5, 5],
       [6, 6],
       [4, 6]])

In [96]:
# select first 2 rows and last 3 columns
data
data[0:2,2:5]

array([[5, 6, 4, 5, 6],
       [6, 5, 2, 6, 6],
       [4, 3, 3, 6, 4]])

array([[4, 5, 6],
       [2, 6, 6]])

### Mean
The Arithmetic Mean is the average of the numbers. It is the sum divided by the count. Mean is represented with the greek letter Mu

<img src='img/mean-01.png' height='40px' width='40px'/>

### Standard Deviation

In statistics, the standard deviation is a measure of the amount of variation of a set of values. A low standard deviation indicates that the values tend to be close to the mean of the set, while a high standard deviation indicates that the values are spread out over a wider range.

<img src='img/std-01.png' />

### Variance

In probability theory and statistics, variance is the expectation of the squared deviation of a random variable from its mean. Informally, it measures how far a set of numbers are spread out from their average value.

<img src='img/var-01.jpg' width='400px' height='400px'/>

### Normal Distribution

Normal distribution, also known as the <b>Gaussian distribution</b>, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean. In graph form, normal distribution will appear as a bell curve.

The simplest case of a normal distribution is known as the standard normal distribution. This is a special case when μ = 0  and σ = 1

<img src='img/normaldistribution-01.png'/>

<b>68-95-99.7 rule</b>

The normal distribution is commonly associated with the 68-95-99.7 rule which you can see in the image above. 
- 68% of the data is within 1 standard deviation (σ) of the mean (μ)
- 95% of the data is within 2 standard deviations (σ) of the mean (μ) 
- 99.7% of the data is within 3 standard deviations (σ) of the mean (μ)

### Pythagoras Theorem
Pythagorean theorem, also known as Pythagoras' theorem, is a fundamental relation in Euclidean geometry among the three sides of a right triangle. It states that the area of the square whose side is the hypotenuse is equal to the sum of the areas of the squares on the other two sides.

Consider the below picture in a (x,y) cordinate system

<img src='img/pyth-02.jpg'/>


If you want to find the distance between the points (x1,y1) and (x2,y2) you could use Pythagoras theorem. 

- Draw a line parallel to x-axis starting from (x1,y1)
- Draw a line parallel to y-axis starting from (x2,y2)
- The point where both the lines meet will be (x2,y1) 
- We have a right angled triangle infront of us and we know
    - |x2-x1|
    - |y2-y1|

To find the distance between (x1,y1) and (x2,y2) let's apply Pythagoras theorem,
 d = SQRT [(x2-x1)² + (y2-y1)²]
 
 This forms the base of our first ML algorithm 'Nearest Neighbour'

### K Nearest Neighbour (KNN) Algorithm

K Nearest Neighbour is a simple algorithm that stores all the available cases and classifies the new data or case based on a similarity measure. It is mostly used to classifies a data point based on how its neighbours are classified.

Let's try to understand this with an example. Consider the marks for 10 students in a class for 5 subjects. Marks range between 35 - 100

In [103]:
#Ignore the 6th column for now, this is a place holder for rank
marks = np.random.randint(35,100,(10,6))
marks

array([[54, 86, 95, 83, 61, 70],
       [60, 48, 92, 37, 86, 58],
       [39, 48, 88, 89, 56, 93],
       [62, 48, 94, 74, 99, 76],
       [46, 41, 63, 86, 39, 98],
       [46, 69, 89, 63, 37, 99],
       [54, 46, 63, 80, 72, 98],
       [44, 60, 91, 96, 82, 89],
       [71, 77, 71, 43, 69, 77],
       [65, 61, 78, 94, 38, 56]])

In [106]:
##### Let's introduce an additional field 'status' to data. status of 0 indicates fail and 1 indicates pass
status = np.random.randint(0,2,(10)) 
marks[:,5] = status
marks

array([[54, 86, 95, 83, 61,  0],
       [60, 48, 92, 37, 86,  0],
       [39, 48, 88, 89, 56,  0],
       [62, 48, 94, 74, 99,  1],
       [46, 41, 63, 86, 39,  0],
       [46, 69, 89, 63, 37,  1],
       [54, 46, 63, 80, 72,  1],
       [44, 60, 91, 96, 82,  0],
       [71, 77, 71, 43, 69,  1],
       [65, 61, 78, 94, 38,  1]])

In [107]:
# A new student joins the class and let's try to assign him a status based on his scores
newstudent = np.array([35,80,67,90,80])
newstudent

array([35, 80, 67, 90, 80])

In [110]:
# extract only subject marks
marks[:,0:5]

array([[54, 86, 95, 83, 61],
       [60, 48, 92, 37, 86],
       [39, 48, 88, 89, 56],
       [62, 48, 94, 74, 99],
       [46, 41, 63, 86, 39],
       [46, 69, 89, 63, 37],
       [54, 46, 63, 80, 72],
       [44, 60, 91, 96, 82],
       [71, 77, 71, 43, 69],
       [65, 61, 78, 94, 38]])

In [111]:
# Let's apply KNN here. We have to find the closest student for the new student in terms of individual subject marks 
# distance between new student and every other student marks
# here we are finding (x2-x1) , (y2-y1), (z2-z1), (m2-m1), (n2-n1)
# x - marks for physics
# y - marks for chemistry
# z - marks for biology
# m - marks for maths
# n - marks for computer science
distance = newstudent - marks[:,0:5]
distance

array([[-19,  -6, -28,   7,  19],
       [-25,  32, -25,  53,  -6],
       [ -4,  32, -21,   1,  24],
       [-27,  32, -27,  16, -19],
       [-11,  39,   4,   4,  41],
       [-11,  11, -22,  27,  43],
       [-19,  34,   4,  10,   8],
       [ -9,  20, -24,  -6,  -2],
       [-36,   3,  -4,  47,  11],
       [-30,  19, -11,  -4,  42]])

In [112]:
# here we are finding (x2-x1)² , (y2-y1)², (z2-z1)², (m2-m1)², (n2-n1)²
distance_square = distance * distance
distance_square

array([[ 361,   36,  784,   49,  361],
       [ 625, 1024,  625, 2809,   36],
       [  16, 1024,  441,    1,  576],
       [ 729, 1024,  729,  256,  361],
       [ 121, 1521,   16,   16, 1681],
       [ 121,  121,  484,  729, 1849],
       [ 361, 1156,   16,  100,   64],
       [  81,  400,  576,   36,    4],
       [1296,    9,   16, 2209,  121],
       [ 900,  361,  121,   16, 1764]])

In [113]:
# here we are finding (x2-x1)² + (y2-y1)² + (z2-z1)² + (m2-m1)² + (n2-n1)²
distance_sum = distance_square.sum(axis=1)
distance_sum

array([1591, 5119, 2058, 3099, 3355, 3304, 1697, 1097, 3651, 3162])

In [114]:
# here we are finding square root of (x2-x1)² + (y2-y1)² + (z2-z1)² + (m2-m1)² + (n2-n1)²
root_distance_sum = np.sqrt(distance_sum)
root_distance_sum

array([39.88734135, 71.54718723, 45.36518489, 55.66866264, 57.92236183,
       57.48043145, 41.19465985, 33.12099032, 60.42350536, 56.23166368])

In [115]:
# Mark of the student that's closer to the new student
root_distance_sum.min()

33.12099032335839

In [116]:
# Position of the student that's clsoser to the new student
position = root_distance_sum.argmin()
closest_student = marks[position]
closest_student

# since the status of the closest student is '0' we assign the status of the new student also as fail 

array([44, 60, 91, 96, 82,  0])

##### We could do all the above steps in a single step too

In [117]:
position = np.sqrt((newstudent - marks[:,0:5])**2).sum(axis=1).argmin()
closest_student = marks[position]
closest_student

array([44, 60, 91, 96, 82,  0])

#### Quick observations on KNN

In the example above we used Euclidean distance method. 

Other methods are Manhattan, Minkowski, and Hamming distance methods. For categorical variables, the hamming distance must be used.

Also - In the above example, we used just one closest neighbour and decided the 'fate' of the new student. One of the hyperparameters we could use in the real KNN algorithm is to decide the value of 'k'. If 'k' is chosen as 3, then we could go for majority vote between the output of 3 nearest neighbour. i.e. if 2 out of 3 said, the student will 'pass', then we go with 'pass' even if one said 'fail'. Go for an odd number of 'k' so that clear majority emerges.

<b>Pros of KNN</b>
- Simple to implement
- Flexible to feature/distance choices
- Naturally handles multi-class cases
- Can do well in practice with enough representative data

<b>Cons of KNN</b>
- Need to determine the value of parameter K (number of nearest neighbors)
- Computation cost is quite high because we need to compute the distance of each query instance to all training samples.
- Storage of data
- Must know we have a meaningful distance function.