In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)


[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[[4. 4.]
 [4. 4.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [ ]:
## In the final output above we coudl take only PCA-1 component for our further analysis.. thereby reducing the dimensions 

In [4]:
# sklearn way of coding the same
from sklearn.decomposition import PCA
A = array([[1,2],[3,4],[5,6]])
print(A)
pca = PCA()
pca.fit(A)
print(pca.components_)
print(pca.explained_variance_)
B = pca.transform(A)
B

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[8.00000000e+00 2.25080839e-33]


array([[-2.82842712e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00, -2.22044605e-16]])

In [5]:
# sklearn way of coding the same
from sklearn.decomposition import PCA
A = array([[1,2],[3,4],[5,6]])
print(A)
pca = PCA(1)
pca.fit(A)
print(pca.components_)
print(pca.explained_variance_)
B = pca.transform(A)
B

[[1 2]
 [3 4]
 [5 6]]
[[0.70710678 0.70710678]]
[8.]


array([[-2.82842712],
       [ 0.        ],
       [ 2.82842712]])

In [ ]:
https://machinelearningmastery.com/adaboost-ensemble-in-python/


PCA
ADA Boosting
Gradient boosting regression
Gradient boosting classification
XGBoost