<h1> Day 19 - Class </h1>

## Introduction to Algebra

Algebra - Meaning is "reunion of broken parts"

### Scalar
A scalar has only a magnitude.

### Vector
A vector quantity has a direction and a magnitude

<img src='img/vector-01.svg'/>

#### Adding vectors
We can add two vectors by joining them head-to-tail:

<img src='img/vector-02.svg'/>

Example: add the vectors a = (8, 13) and b = (26, 7)

c = a + b

c = (8, 13) + (26, 7) = (8+26, 13+7) = (34, 20)

#### Subtracting vectors
We can subtract one vector from another:

<img src='img/vector-03.gif'/>


Example: subtract k = (4, 5) from v = (12, 2)

a = v + −k

a = (12, 2) + −(4, 5) = (12, 2) + (−4, −5) = (12−4, 2−5) = (8, −3)

#### Magnitude of a Vector
The magnitude of a vector is shown by two vertical bars on either side of the vector:

|a|

OR it can be written with double vertical bars (so as not to confuse it with absolute value):

||a||

We use Pythagoras' theorem to calculate it:

|a| = √( x2 + y2 )
Example: what is the magnitude of the vector b = (6, 8) ?

|b| = √( 62 + 82) = √( 36+64) = √100 = 10

A vector with magnitude 1 is called a Unit Vector.

#### Multiplying a Vector by a Scalar

We can multiply a vector by a scalar (called "scaling" a vector): 

<img src='img/vector-04.gif'/>

(And now you know why numbers are called "scalars", because they "scale" the vector up or down.)

#### Multiplying a Vector by a Vector (Dot Product)

For the dot Product the result is a scalar.

The Dot Product is written using a central dot:

a · b

This means the Dot Product of a and b 

We can calculate the Dot Product of two vectors this way: 

<img src='img/dot-01.png'/>

<img src='img/dot-02.png'/>

<img src='img/dot-03.png'/>

When two vectors are at right angles to each other the dot product is zero. Cos 90 = 0

Magnitude of a i.e. |a| can be calculated by using pythagoras theorem as explained in section 1.1.2.3. So, even if the vector is in multiple dimenstions just calculate the root sum of squares.

Now for the other formula:

a · b = |a| × |b| × cos(θ)

But what is |a| ? It is the magnitude, or length, of the vector a. We can use Pythagoras:

    |a| = √(42 + 82 + 102)
    |a| = √(16 + 64 + 100)
    |a| = √180

Likewise for |b|:

    |b| = √(92 + 22 + 72)
    |b| = √(81 + 4 + 49)
    |b| = √134

If we know the θ, we can calulate dot product by using the below formula,

a · b = |a| × |b| × cos(θ)

We can also use the formula,

a · b = ax × bx + ay × by + az × bz

#### Multiplying a Vector by a Vector (Cross Product)

The vector or Cross Product (the result is a vector).

<img src='img/cross-01.png'/>

<img src='img/cross-02.png'/>

The cross product is:

- zero in length when vectors a and b point in the same, or opposite, direction
- reaches maximum length when vectors a and b are at right angles

<img src='img/cross-03.png'/>

<img src='img/cross-04.png'/>

#### Row Vector & Column Vector
A row vector is a 1xn matrix, as it has 1 row and some number of columns. 

A column vector is simply a vector whose components are listed vertically in a single column.

<img src='img/cross-05.png'/>

### Matrix
A <b>square matrix</b> is a matrix with the same number of rows and columns. An n-by-n matrix is known as a square matrix of order n.

For any m-by-n matrix, if we multiply the matrix by it's transpose , then we get a m-by-m square matrix.

<b>Transpose</b> - In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by AT

A matrix multipled by it's <b>inverse</b> will give an <b>identity matrix</b>

### Eigen Values & Eigen Vectors

### Practice

In [3]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [4]:
data = np.random.randint(0,10,(10,3))
data
# here data is a set of vectors .. and a set of vectors is a matrix

array([[5, 3, 3],
       [1, 1, 4],
       [4, 4, 5],
       [1, 1, 9],
       [6, 1, 1],
       [4, 1, 6],
       [1, 3, 4],
       [8, 5, 1],
       [3, 9, 6],
       [3, 5, 2]])

In [5]:
np.add(data,2)
np.add(data[0],2)

# we can do mathematical operations on both vector and matrix

array([[ 7,  5,  5],
       [ 3,  3,  6],
       [ 6,  6,  7],
       [ 3,  3, 11],
       [ 8,  3,  3],
       [ 6,  3,  8],
       [ 3,  5,  6],
       [10,  7,  3],
       [ 5, 11,  8],
       [ 5,  7,  4]])

array([7, 5, 5])

In [6]:
np.subtract(data,2)
np.subtract(data[0],2)

array([[ 3,  1,  1],
       [-1, -1,  2],
       [ 2,  2,  3],
       [-1, -1,  7],
       [ 4, -1, -1],
       [ 2, -1,  4],
       [-1,  1,  2],
       [ 6,  3, -1],
       [ 1,  7,  4],
       [ 1,  3,  0]])

array([3, 1, 1])

In [7]:
np.multiply(data,2)
np.multiply(data[0],2)

array([[10,  6,  6],
       [ 2,  2,  8],
       [ 8,  8, 10],
       [ 2,  2, 18],
       [12,  2,  2],
       [ 8,  2, 12],
       [ 2,  6,  8],
       [16, 10,  2],
       [ 6, 18, 12],
       [ 6, 10,  4]])

array([10,  6,  6])

In [8]:
np.power(data,2)
np.power(data[0],2)

array([[25,  9,  9],
       [ 1,  1, 16],
       [16, 16, 25],
       [ 1,  1, 81],
       [36,  1,  1],
       [16,  1, 36],
       [ 1,  9, 16],
       [64, 25,  1],
       [ 9, 81, 36],
       [ 9, 25,  4]], dtype=int32)

array([25,  9,  9], dtype=int32)

## An introduction to Linear Regression and how the math behind it works

In [9]:
data = np.random.randint(0,30,(10,5))
data

# 10 rows and 5 columns .. 10x5 matrix

array([[29, 27, 10, 22, 19],
       [22, 27, 10,  5, 28],
       [17, 10, 25, 15, 20],
       [ 8, 28,  3,  9,  4],
       [ 3, 26, 17, 26,  9],
       [28,  1, 15, 27, 24],
       [20,  8, 29,  9, 13],
       [ 9, 19, 20, 16, 25],
       [19, 23, 15,  5, 16],
       [26, 24, 29,  8,  0]])

In [10]:
# Let's consider first 4 columns as x1,x2,x3,x4 and 5th column as y
# to access the y value
y = data[:,4]
y

array([19, 28, 20,  4,  9, 24, 13, 25, 16,  0])

In [11]:
# to access x1,x2,x3,x4
x = data[:,0:4]
x

array([[29, 27, 10, 22],
       [22, 27, 10,  5],
       [17, 10, 25, 15],
       [ 8, 28,  3,  9],
       [ 3, 26, 17, 26],
       [28,  1, 15, 27],
       [20,  8, 29,  9],
       [ 9, 19, 20, 16],
       [19, 23, 15,  5],
       [26, 24, 29,  8]])

When there is only one x variable we can represent the relation b/w x and y in a two dimensional space. 

<img src='img/linreg.jpg'/>

we can draw a straight line representing majority of the data set and this is the basic concept of linear regression

when we talk about 3 dimensional space instead of straight line we can visualize a plane

<img src='img/linreg2.png'/>

A line can be represented using the formulae y=mx+c , if there are x1 x2 x3.. then, y = m1x1 + m2x2 + m3x3

The crux of linear regression is to find the beta coefficients, i.e. m1, m2, m3 etc ...

In [12]:
x.shape, y.shape

((10, 4), (10,))

In the above example shape of x & y is 10x4 and 10x1

considering y = mx (ignore + c for now) what should be the shape of m ?

(10,1) = (10,4) * (4,1) --> shape of m should be (4,1)

Let's see how we figure out the value of m 

y = xm

Identify Matrix is a matrix equivalent to 1 in numbers. i.e. any number multiplied by 1 will result in the same number

Two facts :-
- To get identity matrix for a square matrix , we can multiple any square matrix with the inverse of the matrix. 
- Given any matrix we can convert it to a square matrix by multipling it with its own transpose

y = xm <br>

#multiply with transpose of x on either sides to convert into a square matrix <br>
x.T * y = x.T * x * m <br>

#multiply with inv(x.T * x) on either sides so that only m remains in the RHS<br>
inv(x.T * x) * x.T * y = inv(x.T * x) * (x.T * x) * m <br>

Note :- inv is the function for finding the inverse

any matrix multiplied with it's inverse is an identity matrix and equivalent to 1 so in right hand side it's just m

inv(x.T * x) * x.T * y = m

here star (*) is nothing but product


i.e. <b> m = inv(X.T.dot(X)).dot(X.T).dot(y) </b>

Read https://online.stat.psu.edu/stat462/node/132/

### Let's try it for titanic data set. Let's consider 'y' as fare

In [31]:
import numpy as np
import seaborn as sns
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'
df = sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [32]:
# let's consider fare as y value and all numerical columns as x variables.. 
# find beta coefficients
from preprocessing.memory import MemoryUtil
from preprocessing.nv import NVUtil
from numpy.linalg import inv

In [33]:
excluded_columns,selected_columns,numerical_columns,categorical_columns,df = NVUtil.nv_treatment(df,30)
numerical_columns


Before NV treatment the stats are as below
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
Before NV treatment the stats are as below
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64


array(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'],
      dtype=object)

In [34]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  28.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  
0      man        True  Southampton    no  False  
1    woman       False    Cherbourg   yes  False  
2    woman       False  Southampton   yes   True  
3    woman       False  Southampton   yes  False  
4      man        True  Southampton    no   True  
..     ...         ...          ...   ...    ...  
886    man        True  Southampton    no   True  
887  woman       False  Southampton   yes   True  
888  woman       False  Southampton    no  False  
889    man        True    Cherbourg   yes   True  
890    man        True   Queenstown    no   True  

[891 rows x 14 columns]

In [35]:
numerical_columns

array(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'],
      dtype=object)

In [36]:
numerical_columns = numerical_columns[numerical_columns!='fare']
numerical_columns

array(['survived', 'pclass', 'age', 'sibsp', 'parch'], dtype=object)

In [37]:
y = df['fare']
x = df[numerical_columns]

In [38]:
m = inv(x.T.dot(x)).dot(x.T).dot(y)
m

array([ 26.95961925, -10.6804178 ,   1.13788122,   9.25881037,
        12.23388595])

We should apply these values of m , calculate the y and find the difference b/w actual y value and the 
calculated y value. The sum of all such difference is the total 'error'

## References

https://www.mathsisfun.com

https://www.mathsisfun.com/algebra/eigenvalue.html

## TODO

https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab