<h1> Day 3 - Class </h1>

## Matrix
In mathematics, a matrix (plural matrices) is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. For example, the dimension of the matrix below is 2 × 3 (read "two by three"), because there are two rows and three columns: 
[[1, 3, 2],
 [3, 1, 4]]
 
The individual items in an m×n matrix A, often denoted by ai,j, where i and j usually vary from 1 to m and n. A major application of matrices is to represent linear transformations, that is, generalizations of linear functions such as f(x) = 4x. For example, the rotation of vectors in three-dimensional space is a linear transformation, which can be represented by a rotation matrix R: if v is a column vector (a matrix with only one column) describing the position of a point in space, the product Rv is a column vector describing the position of that point after a rotation. 

### Row Vector
Matrices with a single row are called row vectors

### Column Vector
Matrices with a single column are called column vectors

### Square Matrix
A matrix with the same number of rows and columns is called a square matrix.

### Transpose of a Matrix
Transpose of a matrix is an operator which flips a matrix over its diagonal, that is it switches the row and column indices of the matrix by producing another matrix.

<img src='img/tranpose-1.gif'/>

If A is an m × n matrix, then A transpose is an n × m matrix. 

In [3]:
import numpy as np
data = np.random.randint(1,5,(3,2))
data

array([[3, 4],
       [3, 2],
       [4, 2]])

In [4]:
data.T

array([[3, 3, 4],
       [4, 2, 2]])

In [11]:
data.shape, data.T.shape

((10, 5), (5, 10))

### Matrix product
Matrix multiplication is a binary operation that produces a matrix from two matrices. For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The result matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix. 

In [7]:
matrix_one = np.random.randint(1,5,(3,2))
matrix_two = np.random.randint(1,5,(2,4))

In [8]:
# 3 * 2 matrix
matrix_one

array([[2, 1],
       [1, 4],
       [1, 3]])

In [9]:
# 2 * 4 matrix
matrix_two

array([[1, 2, 4, 1],
       [3, 2, 3, 4]])

In [10]:
# 3 * 4 matrix
np.dot(matrix_one, matrix_two)

array([[ 5,  6, 11,  6],
       [13, 10, 16, 17],
       [10,  8, 13, 13]])

#### Product of a matrix and it's transpose gives a square matrix

In [11]:
data

array([[3, 4],
       [3, 2],
       [4, 2]])

In [5]:
np.dot(data, data.T)

array([[25, 17, 20],
       [17, 13, 16],
       [20, 16, 20]])

### Determinant of a matrix
The determinant of a matrix is a special number that can be calculated from a square matrix.

<img src='img/matrix-01.gif'/>

Determinant of the above matrix is calculated as,

3×6 − 8×4 = 18 − 32 = −14

Determinant of a matrix A is represented as |A|

<img src='img/matrix-02.gif'/>

|A| = ad − bc

<img src='img/matrix-03.gif'/>
|A| = a(ei − fh) − b(di − fg) + c(dh − eg)

The determinant of a matrix A is denoted det(A), det A, or |A|. Geometrically, it can be viewed as the volume scaling factor of the linear transformation described by the matrix. This is also the signed volume of the n-dimensional parallelepiped spanned by the column or row vectors of the matrix. The determinant is positive or negative according to whether the linear mapping preserves or reverses the orientation of n-space. 

### Inverse of a matrix
Any number multiplied by it's reciprocal gives 1.  Similarly for a given matrix, if you multiply the matrix and it's inverse matrix, then we get the identity matrix.

<img src='img/inverse-01.svg'/>

In [13]:
# Finding determinant
data = np.random.randint(1,10,(2,2))
data
np.linalg.det(data)

41.999999999999986

In [16]:
# Finding inverse
inverse = np.linalg.inv(data)
inverse

array([[ 0.19047619, -0.16666667],
       [-0.04761905,  0.16666667]])

In [18]:
np.dot(data,inverse)

array([[1., 0.],
       [0., 1.]])

### Crammer's Rule

Cramer's rule is an explicit formula for the solution of a system of linear equations with as many equations as unknowns, valid whenever the system has a unique solution.

Consider the following linear equations,

2x + 3y - 5z = 1

 x +  y -  z = 2
 
2y +  z = 8
     
x = Dx/D

y = Dy/D

z = Dz/D

In [38]:
data = np.array([[2,3,-5],[1,1,-1],[0,2,1]])
data

array([[ 2,  3, -5],
       [ 1,  1, -1],
       [ 0,  2,  1]])

In [42]:
detdata = np.linalg.det(data)
int(detdata)

-6

In [40]:
# replace the first column with 1,2,8
datax =  np.array([[1,3,-5],[2,1,-1],[8,2,1]])

datax

array([[ 1,  3, -5],
       [ 2,  1, -1],
       [ 8,  2,  1]])

In [43]:
detdatax = np.linalg.det(datax)
int(detdatax)

-6

In [29]:
# replace the second column with 1,2,8
datay = np.array([[2,1,-5],[1,2,-1],[0,8,1]])
datay

array([[ 2,  1, -5],
       [ 1,  2, -1],
       [ 0,  8,  1]])

In [44]:
detdatay = np.linalg.det(datay)
int(detdatay)

-21

In [30]:
# replace the third column with 1,2,8
dataz = np.array([[2,3,1],[1,1,2],[0,2,8]])
dataz

array([[2, 3, 1],
       [1, 1, 2],
       [0, 2, 8]])

In [45]:
detdataz = np.linalg.det(dataz)
int(detdataz)

-14

In [49]:
x = int(detdatax)/int(detdata)
int(x)

1

In [51]:
y = int(detdatay)/int(detdata)
int(y)

3

In [50]:
z = int(detdataz)/int(detdata)
int(z)

2

## Querying data from a matrix

In [53]:
data = np.random.randint(0,10,10)
data

array([6, 4, 0, 6, 5, 7, 4, 3, 1, 4])

In [54]:
# This gives an array with True/Fase entries
data > 5

array([ True, False, False,  True, False,  True, False, False, False,
       False])

In [56]:
# This selects only the True entries
data[data > 5]

array([6, 6, 7])

The criteria is that the length of the binary array inside should match with the length of the real array

In [61]:
temp = np.random.randint(0,10,10)
temp

array([9, 5, 9, 9, 5, 6, 6, 8, 1, 2])

In [62]:
temp > 5

array([ True, False,  True,  True, False,  True,  True,  True, False,
       False])

In [63]:
data[temp > 5]

array([6, 0, 6, 7, 4, 3])

In [64]:
data[[True,True,False,False,False,False,False,False,False,False]]

array([6, 4])

In [66]:
marks = np.random.randint(0,100,10)
marks

array([75, 60, 27, 14, 17,  1, 15, 51,  1, 77])

In [68]:
marks[marks > 50]

array([75, 60, 51, 77])

In [70]:
marks[(marks > 50) & (marks < 70)]

array([60, 51])

## Clustering Alogrithm (K-Means)

Cluster analysis, or clustering, is an unsupervised machine learning task. It involves automatically discovering natural grouping in data. Unlike supervised learning (like predictive modeling), clustering algorithms only interpret the input data and find natural groups or clusters in feature space. It is the task of grouping a set of objects in such a way that objects in the same group (called a cluster) are more similar (in some sense) to each other than to those in other groups (clusters).

We have to decide how many clusters are we going to form.

<b> K-Means Algorithm </b>
- Step 1 in the algorithm is to identify the number of clusters that's required to build the algorithm
- If the user requests for 'n' clusters, then we have to create 'n' number of random points
- From random points, find the distance with each row. This leads to for every row 2 distances will be associated(if 'n' == 2)
- Cluster the rows based on minimum distance. Observations that are closer to random point 1 will form cluster-1 , observations that are closer to random point 2 will form cluster-2 and so on

In [19]:
data = np.random.randint(0,10,(100,5))
data[0:5]

array([[9, 6, 8, 5, 6],
       [7, 5, 5, 4, 2],
       [1, 5, 0, 6, 7],
       [1, 7, 7, 5, 8],
       [1, 8, 9, 7, 2]])

##### We are going to create 2 clusters.. so we got to select 2 random samples

In [72]:
random_sample_1 = data[np.random.randint(0,100)]
random_sample_1

array([6, 8, 0, 9, 9])

In [73]:
random_sample_2 = data[np.random.randint(0,100)]
random_sample_2

array([3, 9, 4, 7, 7])

In [76]:
distance_r1 =  np.sqrt(((random_sample_1-data) * (random_sample_1-data)).sum(axis=1))
len(distance_r1)

100

In [77]:
distance_r2 =  np.sqrt(((random_sample_2-data) * (random_sample_2-data)).sum(axis=1))
len(distance_r2)

100

In [79]:
distance_r2 > distance_r1

array([False,  True,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

##### To find all records closer to r1

In [80]:
data[distance_r2 > distance_r1]

array([[6, 8, 0, 9, 9],
       [4, 6, 1, 8, 6],
       [7, 2, 0, 2, 9],
       [6, 2, 2, 7, 5],
       [6, 0, 1, 4, 8],
       [4, 5, 0, 6, 6],
       [9, 9, 0, 9, 7],
       [8, 9, 1, 3, 8],
       [7, 5, 0, 9, 0],
       [7, 1, 0, 6, 3],
       [8, 0, 2, 7, 1]])

##### To find all records closer to r2

In [81]:
data[distance_r1 > distance_r2]

array([[6, 6, 4, 8, 4],
       [2, 8, 8, 5, 1],
       [9, 2, 6, 7, 3],
       [1, 0, 3, 3, 5],
       [9, 7, 8, 1, 5],
       [8, 9, 4, 0, 5],
       [1, 9, 7, 5, 3],
       [3, 0, 9, 5, 2],
       [4, 6, 6, 0, 1],
       [3, 9, 4, 7, 7],
       [7, 9, 9, 4, 9],
       [4, 6, 8, 2, 9],
       [0, 5, 4, 3, 9],
       [1, 7, 7, 9, 5],
       [2, 0, 9, 9, 1],
       [8, 7, 6, 8, 9],
       [1, 3, 2, 6, 5],
       [2, 7, 8, 9, 4],
       [5, 3, 8, 5, 5],
       [9, 2, 8, 2, 6],
       [0, 4, 9, 2, 8],
       [9, 3, 9, 8, 5],
       [8, 5, 1, 2, 1],
       [2, 6, 1, 1, 6],
       [6, 0, 9, 7, 1],
       [6, 4, 2, 2, 9],
       [0, 6, 2, 9, 7],
       [7, 9, 8, 5, 7],
       [0, 8, 4, 0, 5],
       [1, 3, 1, 4, 8],
       [9, 7, 2, 7, 1],
       [3, 7, 5, 1, 6],
       [8, 5, 8, 9, 0],
       [6, 5, 4, 1, 0],
       [9, 6, 8, 0, 1],
       [4, 9, 2, 0, 1],
       [0, 5, 1, 7, 8],
       [4, 2, 4, 3, 4],
       [4, 3, 7, 4, 3],
       [0, 7, 8, 9, 5],
       [3, 1, 9, 2, 5],
       [0, 3, 3,

## Segmentation of bank customers

In [91]:
import seaborn as sns
df = sns.load_dataset("mpg")
dataset = df[['weight','horsepower','mpg']]
dataset.head()
dataset.values.shape

(398, 3)

In [95]:
data = dataset.values

##### Let's pick 3 random points and hence 3 clusters

In [96]:
cluster1 = data[100]
cluster1

array([3021.,   88.,   18.])

In [97]:
cluster2 = data[150]
cluster2

array([2391.,   93.,   26.])

In [98]:
cluster3 = data[200]
cluster3

array([3574.,   78.,   18.])

In [123]:
distance_cluster1 =  np.sqrt(((cluster1-data) * (cluster1-data)).sum(axis=1))

In [124]:
distance_cluster2 =  np.sqrt(((cluster2-data) * (cluster2-data)).sum(axis=1))

In [125]:
distance_cluster3 =  np.sqrt(((cluster3-data) * (cluster3-data)).sum(axis=1))

In [110]:
len(distance_cluster1),len(distance_cluster2),len(distance_cluster3)

(398, 398, 398)

In [112]:
distance_matrix = np.array([distance_cluster1,distance_cluster2,distance_cluster3])

In [113]:
distance_matrix.shape

(3, 398)

In [114]:
distance_matrix_t = distance_matrix.T
distance_matrix_t.shape

(398, 3)

##### Find the min value in each row and it's index position.. The position represents each cluster

In [116]:
distance_flag = distance_matrix_t.argmin(axis=1)

In [117]:
### To find records falling in cluster 1 
data[distance_flag == 0]

array([[3504. ,  130. ,   18. ],
       [3693. ,  165. ,   15. ],
       [3436. ,  150. ,   18. ],
       [3433. ,  150. ,   16. ],
       [3449. ,  140. ,   17. ],
       [4341. ,  198. ,   15. ],
       [4354. ,  220. ,   14. ],
       [4312. ,  215. ,   14. ],
       [4425. ,  225. ,   14. ],
       [3850. ,  190. ,   15. ],
       [3563. ,  170. ,   15. ],
       [3609. ,  160. ,   14. ],
       [3761. ,  150. ,   15. ],
       [3086. ,  225. ,   14. ],
       [2833. ,   95. ,   22. ],
       [2774. ,   97. ,   18. ],
       [4615. ,  215. ,   10. ],
       [4376. ,  200. ,   10. ],
       [4382. ,  210. ,   11. ],
       [4732. ,  193. ,    9. ],
       [2046. ,    nan,   25. ],
       [3439. ,  105. ,   16. ],
       [3329. ,  100. ,   17. ],
       [3302. ,   88. ,   19. ],
       [3288. ,  100. ,   18. ],
       [4209. ,  165. ,   14. ],
       [4464. ,  175. ,   14. ],
       [4154. ,  153. ,   14. ],
       [4096. ,  150. ,   14. ],
       [4955. ,  180. ,   12. ],
       [47

In [118]:
data[distance_flag == 1]

array([[2372. ,   95. ,   24. ],
       [2587. ,   85. ,   21. ],
       [2130. ,   88. ,   27. ],
       [1835. ,   46. ,   26. ],
       [2672. ,   87. ,   25. ],
       [2430. ,   90. ,   24. ],
       [2375. ,   95. ,   25. ],
       [2234. ,  113. ,   26. ],
       [2648. ,   90. ,   21. ],
       [2130. ,   88. ,   27. ],
       [2264. ,   90. ,   28. ],
       [2228. ,   95. ,   25. ],
       [2634. ,  100. ,   19. ],
       [2408. ,   72. ,   22. ],
       [2220. ,   86. ,   23. ],
       [2123. ,   90. ,   28. ],
       [2074. ,   70. ,   30. ],
       [2065. ,   76. ,   30. ],
       [1773. ,   65. ,   31. ],
       [1613. ,   69. ,   35. ],
       [1834. ,   60. ,   27. ],
       [1955. ,   70. ,   26. ],
       [2278. ,   95. ,   24. ],
       [2126. ,   80. ,   25. ],
       [2254. ,   54. ,   23. ],
       [2408. ,   90. ,   20. ],
       [2226. ,   86. ,   21. ],
       [2330. ,   97. ,   19. ],
       [2511. ,   76. ,   22. ],
       [2189. ,   69. ,   26. ],
       [23

In [120]:
data[distance_flag == 2]

array([], shape=(0, 3), dtype=float64)

In [122]:
data[distance_flag == 0].shape,data[distance_flag == 1].shape,data[distance_flag == 2].shape

((216, 3), (182, 3), (0, 3))

## NumPy array broadcasting