In [3]:
import numpy as np
data = np.random.randint(1,5,(3,3))
data

array([[4, 3, 1],
       [1, 1, 2],
       [4, 2, 4]])

In [6]:
data.sum(axis=1)

array([ 8,  4, 10])

In [8]:
data = np.random.randint(0,10,(10,5))
data

array([[5, 1, 4, 8, 5],
       [8, 7, 1, 1, 1],
       [5, 4, 1, 4, 8],
       [7, 6, 5, 6, 0],
       [2, 5, 7, 2, 7],
       [7, 1, 5, 1, 9],
       [5, 5, 1, 9, 6],
       [0, 8, 1, 9, 1],
       [2, 0, 7, 2, 7],
       [9, 2, 3, 7, 8]])

### Tranpose of a matrix is data.T

In [9]:
data.T

array([[5, 8, 5, 7, 2, 7, 5, 0, 2, 9],
       [1, 7, 4, 6, 5, 1, 5, 8, 0, 2],
       [4, 1, 1, 5, 7, 5, 1, 1, 7, 3],
       [8, 1, 4, 6, 2, 1, 9, 9, 2, 7],
       [5, 1, 8, 0, 7, 9, 6, 1, 7, 8]])

In [11]:
data.shape, data.T.shape

((10, 5), (5, 10))

### dot product of a matrix (Matrix Multiplication)

In [12]:
np.dot(data, data.T)

array([[131,  64, 105, 109,  94, 109, 136,  89,  89, 155],
       [ 64, 116,  81, 109,  67,  78,  91,  67,  32, 104],
       [105,  81, 122,  88, 101, 120, 130,  77,  81, 148],
       [109, 109,  88, 146,  91,  86, 124, 107,  61, 132],
       [ 94,  67, 101,  91, 131, 119, 102,  72, 106, 119],
       [109,  78, 120,  86, 119, 157, 108,  31, 114, 159],
       [136,  91, 130, 124, 102, 108, 168, 128,  77, 169],
       [ 89,  67,  77, 107,  72,  31, 128, 147,  32,  90],
       [ 89,  32,  81,  61, 106, 114,  77,  32, 106, 109],
       [155, 104, 148, 132, 119, 159, 169,  90, 109, 207]])

In [13]:
np.dot(data, data.T).shape

(10, 10)

### Dot product of a matrix and it's transpose gives a square matrix 

### square matrix has equal number of rows and columns

### Krammer's Rule

In [38]:
data = np.array([[2,3,-5],[1,1,-1],[0,2,1]])
data

array([[ 2,  3, -5],
       [ 1,  1, -1],
       [ 0,  2,  1]])

In [42]:
detdata = np.linalg.det(data)
int(detdata)

-6

In [40]:
datax =  np.array([[1,3,-5],[2,1,-1],[8,2,1]])

datax

array([[ 1,  3, -5],
       [ 2,  1, -1],
       [ 8,  2,  1]])

In [43]:
detdatax = np.linalg.det(datax)
int(detdatax)

-6

In [29]:
datay = np.array([[2,1,-5],[1,2,-1],[0,8,1]])
datay

array([[ 2,  1, -5],
       [ 1,  2, -1],
       [ 0,  8,  1]])

In [44]:
detdatay = np.linalg.det(datay)
int(detdatay)

-21

In [30]:
dataz = np.array([[2,3,1],[1,1,2],[0,2,8]])
dataz


array([[2, 3, 1],
       [1, 1, 2],
       [0, 2, 8]])

In [45]:
detdataz = np.linalg.det(dataz)
int(detdataz)

-14

In [49]:
x = int(detdatax)/int(detdata)
int(x)

1

In [51]:
y = int(detdatay)/int(detdata)
int(y)

3

In [50]:
z = int(detdataz)/int(detdata)
int(z)


2

### Querying data from a matrix

In [53]:
data = np.random.randint(0,10,10)
data

array([6, 4, 0, 6, 5, 7, 4, 3, 1, 4])

In [54]:
data > 5

array([ True, False, False,  True, False,  True, False, False, False,
       False])

In [56]:
data[data > 5]

array([6, 6, 7])

### Basic condition is the length of the binary array should equal the length of the array on which the query is applied

In [61]:
temp = np.random.randint(0,10,10)
temp

array([9, 5, 9, 9, 5, 6, 6, 8, 1, 2])

In [62]:
temp > 5

array([ True, False,  True,  True, False,  True,  True,  True, False,
       False])

In [63]:
data[temp > 5]

array([6, 0, 6, 7, 4, 3])

In [64]:
data[[True,True,False,False,False,False,False,False,False,False]]

array([6, 4])

In [66]:
marks = np.random.randint(0,100,10)
marks

array([75, 60, 27, 14, 17,  1, 15, 51,  1, 77])

In [68]:
marks[marks > 50]

array([75, 60, 51, 77])

In [70]:
marks[(marks > 50) & (marks < 70)]

array([60, 51])

### Clustering Alogrithms

In [71]:
data = np.random.randint(0,10,(100,5))
data

array([[6, 6, 4, 8, 4],
       [6, 8, 0, 9, 9],
       [4, 6, 1, 8, 6],
       [2, 8, 8, 5, 1],
       [8, 7, 5, 7, 9],
       [9, 2, 6, 7, 3],
       [1, 0, 3, 3, 5],
       [9, 7, 8, 1, 5],
       [8, 9, 4, 0, 5],
       [8, 5, 1, 4, 3],
       [1, 9, 7, 5, 3],
       [3, 0, 9, 5, 2],
       [4, 6, 6, 0, 1],
       [7, 2, 0, 2, 9],
       [3, 9, 4, 7, 7],
       [7, 9, 9, 4, 9],
       [4, 6, 8, 2, 9],
       [0, 5, 4, 3, 9],
       [1, 7, 7, 9, 5],
       [2, 0, 9, 9, 1],
       [6, 2, 2, 7, 5],
       [8, 7, 6, 8, 9],
       [1, 3, 2, 6, 5],
       [2, 7, 8, 9, 4],
       [5, 3, 8, 5, 5],
       [7, 2, 0, 2, 3],
       [9, 2, 8, 2, 6],
       [0, 4, 9, 2, 8],
       [9, 3, 9, 8, 5],
       [8, 5, 1, 2, 1],
       [2, 6, 1, 1, 6],
       [6, 0, 9, 7, 1],
       [6, 4, 2, 2, 9],
       [0, 6, 2, 9, 7],
       [7, 9, 8, 5, 7],
       [0, 8, 4, 0, 5],
       [1, 3, 1, 4, 8],
       [9, 7, 2, 7, 1],
       [6, 0, 1, 4, 8],
       [3, 7, 5, 1, 6],
       [8, 5, 8, 9, 0],
       [4, 5, 0,

In [74]:
### we are going to create 2 clusters.. so we select 2 random samples

In [72]:
r1 = data[np.random.randint(0,100)]
r1

array([6, 8, 0, 9, 9])

In [73]:
r2 = data[np.random.randint(0,100)]
r2

array([3, 9, 4, 7, 7])

In [76]:
distance_r1 =  np.sqrt(((r1-data) * (r1-data)).sum(axis=1))
len(distance_r1)

100

In [77]:
distance_r2 =  np.sqrt(((r2-data) * (r2-data)).sum(axis=1))
len(distance_r2)

100

In [79]:
distance_r2 > distance_r1

array([False,  True,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
### To find all records closer to r1

In [80]:
data[distance_r2 > distance_r1]

array([[6, 8, 0, 9, 9],
       [4, 6, 1, 8, 6],
       [7, 2, 0, 2, 9],
       [6, 2, 2, 7, 5],
       [6, 0, 1, 4, 8],
       [4, 5, 0, 6, 6],
       [9, 9, 0, 9, 7],
       [8, 9, 1, 3, 8],
       [7, 5, 0, 9, 0],
       [7, 1, 0, 6, 3],
       [8, 0, 2, 7, 1]])

In [ ]:
### To find all records closer to r2

In [81]:
data[distance_r1 > distance_r2]

array([[6, 6, 4, 8, 4],
       [2, 8, 8, 5, 1],
       [9, 2, 6, 7, 3],
       [1, 0, 3, 3, 5],
       [9, 7, 8, 1, 5],
       [8, 9, 4, 0, 5],
       [1, 9, 7, 5, 3],
       [3, 0, 9, 5, 2],
       [4, 6, 6, 0, 1],
       [3, 9, 4, 7, 7],
       [7, 9, 9, 4, 9],
       [4, 6, 8, 2, 9],
       [0, 5, 4, 3, 9],
       [1, 7, 7, 9, 5],
       [2, 0, 9, 9, 1],
       [8, 7, 6, 8, 9],
       [1, 3, 2, 6, 5],
       [2, 7, 8, 9, 4],
       [5, 3, 8, 5, 5],
       [9, 2, 8, 2, 6],
       [0, 4, 9, 2, 8],
       [9, 3, 9, 8, 5],
       [8, 5, 1, 2, 1],
       [2, 6, 1, 1, 6],
       [6, 0, 9, 7, 1],
       [6, 4, 2, 2, 9],
       [0, 6, 2, 9, 7],
       [7, 9, 8, 5, 7],
       [0, 8, 4, 0, 5],
       [1, 3, 1, 4, 8],
       [9, 7, 2, 7, 1],
       [3, 7, 5, 1, 6],
       [8, 5, 8, 9, 0],
       [6, 5, 4, 1, 0],
       [9, 6, 8, 0, 1],
       [4, 9, 2, 0, 1],
       [0, 5, 1, 7, 8],
       [4, 2, 4, 3, 4],
       [4, 3, 7, 4, 3],
       [0, 7, 8, 9, 5],
       [3, 1, 9, 2, 5],
       [0, 3, 3,

In [ ]:
### Segmentation of bank customers

In [91]:
import seaborn as sns
df = sns.load_dataset("mpg")
dataset = df[['weight','horsepower','mpg']]
dataset.head()
dataset.values.shape

(398, 3)

In [95]:
data = dataset.values

In [96]:
cluster1 = data[100]
cluster1

array([3021.,   88.,   18.])

In [97]:
cluster2 = data[150]
cluster2

array([2391.,   93.,   26.])

In [98]:
cluster3 = data[200]
cluster3

array([3574.,   78.,   18.])

In [123]:
distance_cluster1 =  np.sqrt(((cluster1-data) * (cluster1-data)).sum(axis=1))

In [124]:
distance_cluster2 =  np.sqrt(((cluster2-data) * (cluster2-data)).sum(axis=1))

In [125]:
distance_cluster3 =  np.sqrt(((cluster3-data) * (cluster3-data)).sum(axis=1))

In [110]:
len(distance_cluster1),len(distance_cluster2),len(distance_cluster3)

(398, 398, 398)

In [112]:
distance_matrix = np.array([distance_cluster1,distance_cluster2,distance_cluster3])

In [113]:
distance_matrix.shape

(3, 398)

In [ ]:
### above we got 3 rows and 398 columns.. if we want to get 398 rows and 3 columns do a transpose

In [114]:
distance_matrix_t = distance_matrix.T
distance_matrix_t.shape

(398, 3)

In [115]:
### below line finds the min value for each row and it's argument.. The argument represents each cluster

In [116]:
distance_flag = distance_matrix_t.argmin(axis=1)

In [117]:
### To find records falling in cluster 1 
data[distance_flag == 0]

array([[3504. ,  130. ,   18. ],
       [3693. ,  165. ,   15. ],
       [3436. ,  150. ,   18. ],
       [3433. ,  150. ,   16. ],
       [3449. ,  140. ,   17. ],
       [4341. ,  198. ,   15. ],
       [4354. ,  220. ,   14. ],
       [4312. ,  215. ,   14. ],
       [4425. ,  225. ,   14. ],
       [3850. ,  190. ,   15. ],
       [3563. ,  170. ,   15. ],
       [3609. ,  160. ,   14. ],
       [3761. ,  150. ,   15. ],
       [3086. ,  225. ,   14. ],
       [2833. ,   95. ,   22. ],
       [2774. ,   97. ,   18. ],
       [4615. ,  215. ,   10. ],
       [4376. ,  200. ,   10. ],
       [4382. ,  210. ,   11. ],
       [4732. ,  193. ,    9. ],
       [2046. ,    nan,   25. ],
       [3439. ,  105. ,   16. ],
       [3329. ,  100. ,   17. ],
       [3302. ,   88. ,   19. ],
       [3288. ,  100. ,   18. ],
       [4209. ,  165. ,   14. ],
       [4464. ,  175. ,   14. ],
       [4154. ,  153. ,   14. ],
       [4096. ,  150. ,   14. ],
       [4955. ,  180. ,   12. ],
       [47

In [118]:
data[distance_flag == 1]

array([[2372. ,   95. ,   24. ],
       [2587. ,   85. ,   21. ],
       [2130. ,   88. ,   27. ],
       [1835. ,   46. ,   26. ],
       [2672. ,   87. ,   25. ],
       [2430. ,   90. ,   24. ],
       [2375. ,   95. ,   25. ],
       [2234. ,  113. ,   26. ],
       [2648. ,   90. ,   21. ],
       [2130. ,   88. ,   27. ],
       [2264. ,   90. ,   28. ],
       [2228. ,   95. ,   25. ],
       [2634. ,  100. ,   19. ],
       [2408. ,   72. ,   22. ],
       [2220. ,   86. ,   23. ],
       [2123. ,   90. ,   28. ],
       [2074. ,   70. ,   30. ],
       [2065. ,   76. ,   30. ],
       [1773. ,   65. ,   31. ],
       [1613. ,   69. ,   35. ],
       [1834. ,   60. ,   27. ],
       [1955. ,   70. ,   26. ],
       [2278. ,   95. ,   24. ],
       [2126. ,   80. ,   25. ],
       [2254. ,   54. ,   23. ],
       [2408. ,   90. ,   20. ],
       [2226. ,   86. ,   21. ],
       [2330. ,   97. ,   19. ],
       [2511. ,   76. ,   22. ],
       [2189. ,   69. ,   26. ],
       [23

In [120]:
data[distance_flag == 2]

array([], shape=(0, 3), dtype=float64)

In [122]:
data[distance_flag == 0].shape,data[distance_flag == 1].shape,data[distance_flag == 2].shape

((216, 3), (182, 3), (0, 3))